services:
  - type: web
    name: rpjg-dcbot-cloud
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production

